version: '3'

services:
  wolproxypyweb:
    image: wolproxypyweb:latest
    build: .
    container_name: wolproxypyweb
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./logs:/logs
      - ./db:/db
    env_file:
      - .env
    environment:
      - API_PROTO=${API_PROTO}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET})
      - SECRET_KEY=${SECRET_KEY}
    user: "${UID}:${GID}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
