version: '3'

services:
  wolproxypy:
    image: wolproxypyweb:latest
    build: .
    container_name: wolproxypyweb
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./logs:/logs
      - ./db:/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
